[package]
name = "mpv-ipc"
version = "0.1.0"
authors = ["Hamid R. K. Pishghadam <hamidrkp@riseup.net>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.59"
log = "0.4.13"
